blog/accountapp/urls.py
from django.contrib import admin
from django.urls import path, include #include 추가
from accountapp.views import * #views.py의 funtion, class view들을 불러온다
from django.contrib.auth.views import LoginView, LogoutView  #django 내장 Login/Logout View를 불러온다.

#urls.path(route, view, kwrags=None, name=None,Pattern=)

app_name='accountapp' #하면 좋음. 계속 쳐야 하니 그냥 이름 변수에 저장


urlpatterns = [
    #path('hello_world/', hello_world, name='hello_world'),
    
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'), #로그인 view는 따로 템플릿 설정. 괄호 위치 주의. 
    path('logout/', LogoutView.as_view(), name='logout'), #로그아웃 뷰는 없어도 됨.
    
    path('create/', AccountCreateView.as_view(), name='create'), #class형 view는 이후에 .as_view()를 적어야 한다.
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'), #<int:pk>는 접속 사용자 각각의 개별 구별자이다 (primary key)
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

blog/articleapp/urls.py
from articleapp.views import *
from django.urls import path
from django.views.generic import TemplateView #django 기본 제공 view이다. 

app_name='articleapp'


urlpatterns = [
    #path('list/', TemplateView.as_view(template_name='articleapp/list.html'), name='list'),
    path('list/', ArticleListView.as_view(template_name='articleapp/list.html'), name='list'),
    path('create/', ArticleCreateView.as_view(template_name='articleapp/create.html'), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(template_name='articleapp/detail.html'), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(template_name='articleapp/update.html'), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(template_name='articleapp/delete.html'), name='delete'),
]

blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include, reverse #include 추가
#미디어 라우팅을 위한 import 
from django.conf.urls.static import static #static 안의 static이다
from django.conf import settings
from articleapp.views import ArticleListView

urlpatterns = [
    path('', ArticleListView.as_view(), name='home'),
    
    path('admin/', admin.site.urls),
    path('accounts/',include('accountapp.urls')), # ,까지 
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('subscribes/', include('subscribeapp.urls')),
    #소셜 로그인 앱
    path('socialauth/', include('socialauth.urls')),
    path('social-auth/', include('social_django.urls', namespace="social")), #이건 꼭 최상위 urls.py에 써줘야 한다.
    #allauth
    path('accounts/', include('allauth.urls')),
    
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/profileapp/urls.py
from profileapp.views import *
from django.urls import path

app_name='profileapp'


urlpatterns = [
    path('create/', ProfileCreateView.as_view(), name='create'),
    path('update/<int:pk>', ProfileUpdateView.as_view(), name='update'),
        path('list/', ProfileListView.as_view(), name='list'),

]

blog/projectapp/urls.py
from django.urls import include, path
from projectapp.views import *


app_name = 'projectapp'

urlpatterns=[
    path('list/', ProjectListView.as_view(), name='list'),
    path('detail/<int:pk>', ProjectDetailView.as_view(), name='detail'),
    path('create/', ProjectCreateView.as_view(), name='create'),
    path('delete/<int:pk>', ProjectDeleteView.as_view(), name='delete'),
    path('update/<int:pk>', ProjectUpdateView.as_view(), name='update'),
]
    

blog/templates/base.html
<!DOCTYPE html>
<html lang='ko'>
    {% include 'head.html' %} <!-- 경로를 어떻게 아냐? 바로 blog/blog/settings.py에 TEMPLATE 설정에 디렉토리가 지정되어 있다. -->
    <body style="font-family:'NanumSquareR';" class="line-numbers">
        {% include 'header.html' %} <!--재사용을 위해 헤더와 푸터는 분리해 include 한다.-->
        <hr> 
<!--extends 구문을 사용하기 위해 block을 만들어야 한다?-->
<!-- 이걸 사용하기 위해 accountapp 폴더 내부에 templates, 그 안에 또 accountapp이라는 폴더를 만들고 그 안에 html 파일을 넣어준다. view에서 html파일 가져온 경로를 어느 앱인지 알기 쉽게 하기 위해서 -->
        {% block content %} 
        
        
        
        {% endblock %}
        <hr>
        
        {% include 'footer.html' %}
    </body>
</html>

blog/templates/footer.html
<div class="dove_footer">  
    
    <div class="dove_footer_btn" style="font-size:.9rem;">
        <span><a href="https://u-lokr.run.goorm.site/articles/detail/38">소개</a></span> |
        <span><a href="https://u-lokr.run.goorm.site/projects/detail/13">공지사항</a></span> |
        <span><a href="https://u-lokr.run.goorm.site/articles/detail/38">문의하기</a></span> |

    </div>
    
    <div style="margin-top:1rem;">
        <h6>계속해서 개발중입니다. @u-lokr</h6>
    </div>
    
    
    
    
    
</div>

blog/templates/head.html
{% load static %}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <!--부트스트랩 -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css">
    
    <!--폰트 (구글 폰트 이용)-->
    <!-- robster -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
    
    <!-- comfortaa -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Comfortaa:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <meta title='base'>
    
    <!-- noto sans korean -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;300;400;500;700&display=swap" rel="stylesheet">
    
    <!-- 여기까지 폰트 -->
    
    
    <!-- Google meterial icons-->
    <!-- 아이콘 종류는 https://fonts.google.com/icons?selected=Material+Icons 에서 검색-->
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" rel="stylesheet">
    <!-- <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" /> -->
    
    <!-- fontawesome 아이콘 -->
    <script src="https://kit.fontawesome.com/8d225cd6e0.js" crossorigin="anonymous"></script>
    
    <!-- favicon -->
    <link rel="shortcut icon" href="{% static 'icons/favicon.svg' %}">
    
    
    <!--- prismjs -->
    <link href="{% static 'prism.css' %}" rel="stylesheet">
    <script src="{% static 'js/prism.js' %}"></script>
    
    <!-- 소셜 로그인을 위한 것들 -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
        crossorigin="anonymous" />
    
    <!-- CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}"> <!-- setting.py에서 STATIC_URL이 static이다-->
    <style>
        @font-face {
            font-family : 'NanumSquareR';
            src : local('NanumSquareR'),
            url("{% static 'fonts/NanumSquareR.otf' %}") format("opentype");
        }
        
        @font-face {
            font-family : 'NanumSquareB';
            src : local('NanumSquareB'),
            url("{% static 'fonts/NanumSquareB.otf' %}") format("opentype");
        }
        
        @font-face {
            font-family : 'NanumSquareEB';
            src : local('NanumSquareEB'),
            url("{% static 'fonts/NanumSquareEB.otf' %}") format("opentype");
        }
        
        @font-face {
            font-family : 'NanumSquareL';
            src : local('NanumSquareL'),
            url("{% static 'fonts/NanumSquareL.otf' %}") format("opentype");
        }
        
        
    </style>
</head>

blog/templates/header.html
{% load static %}
<style>
    .header_sticky{
        position: fixed;
        top : 0rem;
        box-shadow: 0 4px 12px rgb(0 0 0 / 7%);
        z-index : 1;
        background-color : #f8f9fa;
        width : 100%;

    }
    
        .dove_header button {
        display : none;
          position:fixed;
          top:15px;
          right:20px;
          background-color:#639;
          padding:15px;
          border:none;
          outline: none;
          color: white;    
          transition: transform 0.3s ease-in-out;
        }

        .dove_header button.active {
          transform:translateX(-110px);

        }
        .dove_header nav {
          position:fixed;
          top:0;
          right:0;
          background-color:#639;  
          height:100vh;
          padding:2em;
          transform:translateX(100%);
          transition: transform 0.3s ease-in-out;
        }

        .dove_header nav.active {
          transform:translateX(0);
        }

        .dove_header nav ul {  
          padding:0;
          margin:0;
          list-style: none;
        }

        .dove_header nav ul li {
          padding:1em 0;
        }

        .dove_header nav a {
          color:white;
          text-decoration: none;
        }
    </style>

<div class="dove_header" id="site_header">
    <!-- 타이틀 영역-->
    <div class="dove_logo">
        <i><a href="{% url 'home' %}"><img src="{% static 'icons/favicon.svg' %}"></a></i>
        <h2><a href="{% url 'home' %}"></a></h2>
    </div>
    <!-- rem은 상위 요소의 상대적 크기로 지정. body의 상대적 크기로 각 영역을 나누고 (이번엔 10, 20 ,10이다)내용을 채워넣는다. rem을 적극 이용하자. 나머지 여백 조정 등을 한다.-->
    
    <!-- 내비게이션 바 영역-->
    <div style="font-size:.7rem; display:inline;">
        <a href="{% url 'articleapp:list' %}">
            <span>게시글</span> 
        </a> |
        <a href="{% url 'projectapp:list' %}">
            <span>게시판</span>
        </a> |
        <a href="{% url 'profileapp:list' %}">
            <span>Users</span>
        </a> |
        
        
        {% if not user.is_authenticated %}
        <a href="{% url 'accountapp:login' %}?next={{ request.path }}"> <!-- login 이후 redirect는 1. next 인자, 2. LOGIN_REDIRECT_URL (settings.py)를 통해 redirect됨.-->
            <span>Login</span> 
        </a> |
        <a href="{% url 'accountapp:create' %}">
        	<span>Signup</span>
        </a>
        {% else %}
         <a href="#">
            <span>구독</span>
        </a> |
        <a href="{% url 'accountapp:detail' pk=user.pk %}"> <!-- 이렇게 하면 접속 시 user의 pk를 같이 넘겨준다-->
            <span>마이페이지</span> 
        </a> |
        <a href="{% url 'accountapp:logout' %}?next={{ request.path }}">
            <span>logout</span>
        </a>
        {% endif %}
    </div>
    
    
    <button class="material-symbols-outlined" id="navbtn" style="position:fixed; right: 1rem;">menu</button>
    <nav id="navlist">
        <ul>
            <li>manu1</li>
            <li>menu2</li>
            <li>menu3</li>
            <li>menu4</li>
        </ul>
    </nav>
</div>
<script>
    const navbtn = document.getElementById("navbtn");
    const navlist = document.getElementById("navlist");
    navbtn.addEventListener('click', ()=>{
       navbtn.classList.toggle('active');
        navlist.classList.toggle('active');
    });
    
    // // 스크롤 감지해서 그림자 만들기
    // window.addEventListener('scroll', (e)=>{
    //    const header = document.getElementById('site_header');
    //     if(window.pageYOffset > 0){
    //         header.classList.add('header_sticky');
    //     }else{
    //         header.classList.remove('header_sticky');
    //     }
    // });
</script>

blog/templates/list.html
{% load static %} <!-- static 쓰려면 꼭 해줘야 함-->

{% block content %}
        
<!-- CSS 불러오기 -->
{% include 'articleapp/articleListDesign.css' %}

<script type="application/javascript">
    function photoview(){
        document.getElementById('list').style.display = "none";
        document.getElementById('listselect').style.backgroundColor = "white";
        
        document.getElementById('grid').style.display = "none";
        document.getElementById('gridselect').style.backgroundColor = "white";
        
        document.getElementById('photo').style.display = "block";
        document.getElementById('photoselect').style.backgroundColor = "#f2f2f2";
        magicGrid.positionItems();
        
    }
    
    function listview(){
        document.getElementById('list').style.display = "block";
        document.getElementById('listselect').style.backgroundColor = "#f2f2f2";
        
        document.getElementById('grid').style.display = "none";
        document.getElementById('gridselect').style.backgroundColor = "white";
        
        document.getElementById('photo').style.display = "none";
        document.getElementById('photoselect').style.backgroundColor = "white";
    }
    
    function gridview(){
        document.getElementById('photo').style.display = "none";
        document.getElementById('photoselect').style.backgroundColor = "white";
        
        document.getElementById('grid').style.display = "grid";
        document.getElementById('gridselect').style.backgroundColor = "#f2f2f2";
        
        document.getElementById('list').style.display = "none";
        document.getElementById('gridselect').style.backgroundColor = "white";
    }


</script>
<!-- 목록 표시 상단 영역-->  
<hr>

<div style="display:inline; margin:auto 1rem;">
    <b>전체글</b>
</div>

<!-- 아이콘 내비게이션 바 -->

<div style="display:inline; float:right; margin:auto 1rem;">
    {% if user.is_authenticated %}
    <a href="{% url 'articleapp:create' %}" class="material-icons" style="box-shadow:0 0 2px #ccc;text-align:right;
              background-color: wtite;">
        edit_square
    </a>
    {% endif %}
    
    <!-- gridview는 post형식 -->
    <a href="javascript:void(0);" onclick="gridview()"
       style="box-shadow:0 0 2px #ccc;text-align:right;
              background-color: #f2f2f2;" class="material-icons" id="gridselect">
        grid_view
    </a>
    
    
    <a href="javascript:void(0);" onclick="photoview();" style="box-shadow:0 0 2px #ccc;
              text-align:right; background-color: white;" class="material-symbols-outlined" id="photoselect">
        photo
    </a>
    
    <a href="javascript:void(0);" onclick="listview();"
       style="box-shadow:0 0 2px #ccc;
              text-align:right;
              background-color: white;" class="material-icons" id="listselect">
        view_list
    </a>
</div>
    
<hr style="border: rgba(0,0,0,0);">


    
    <!-- grid로 표시(기본값) -->
    
    <!-- grid(postcard) 형식으로 표시 -->
    {% if article_list %} <!--article_list가 존재한다면-->
    <div class="container_postcard" id="grid">
        {% for article in article_list %} <!-- view에서 context_object_name이다 최신이 위로-->    
        <a href="{% url 'articleapp:detail' pk=article.pk %}">
            {% if article.image %}
            {% include 'snippets/article_list_postcard.html' with article=article %} <!-- for문에 썼던 변수를 전달하기 위함(전달할 이름 = 전달할 내용)-->
            {% else %}
            {% include 'snippets/article_list_postcard_noimage.html' %}
            {% endif %}
        </a>
        {% endfor %}
    </div>
    <!-- <script src="{% static 'js/magicgrid.js' %}"></script> -->
    {% else %}
    <div style="text-align:center;">
        <h1>
            게시글이 존재하지 않습니다.
        </h1>    
    </div>
    {% endif %}


    <!-- photo (magicGrid 사용)힌 형식으로 표시-->
    {% if article_list %} <!--article_list가 존재한다면-->
    <div class="container" id="photo">
        {% for article in article_list %} <!-- view에서 context_object_name이다 최신이 위로-->    
        <a href="{% url 'articleapp:detail' pk=article.pk %}">
            {% include 'snippets/card.html' with article=article %} <!-- for문에 썼던 변수를 전달하기 위함(전달할 이름 = 전달할 내용)-->
        </a>
        {% endfor %}
    </div>
    <script src="{% static 'js/magicgrid.js' %}"></script> <!-- container라는 클래스를 js에서 사용하므로 안에다가 넣어준다-->
    {% else %}
    <div style="text-align:center;">
        <h1>
            게시글이 존재하지 않습니다.
        </h1>    
    </div>
    {% endif %}

    
    
    <!-- list로 표시 -->
     {% if article_list %} 
    <div class="container_list" id="list">
        {% for article in article_list %}
        <a href="{% url 'articleapp:detail' pk=article.pk %}">
            {% include 'snippets/list_article_card.html' with article=article %} 
        </a>
        <hr>
        {% endfor %}
    </div>
    {% else %}
    <div style="text-align:center;">
        <h1>
            게시글이 존재하지 않습니다.
        </h1>    
    </div>
    {% endif %}
    

    





<!-- pagination, create 영역 -->
    {% include 'snippets/pagination.html' with page_obj=page_obj %}
    

    <div style="text-align:center;">
        <a href="{% url 'articleapp:create' %}" class="btn btn-dark rounded-pill px-3 mt-3 mb-3">
        새 글 작성하기
        </a>
    </div>


{% endblock %}