blog/accountapp/urls.py
from django.contrib import admin
from django.urls import path, include #include 추가
from accountapp.views import * #views.py의 funtion, class view들을 불러온다
from django.contrib.auth.views import LoginView, LogoutView  #django 내장 Login/Logout View를 불러온다.

#urls.path(route, view, kwrags=None, name=None,Pattern=)

app_name='accountapp' #하면 좋음. 계속 쳐야 하니 그냥 이름 변수에 저장


urlpatterns = [
    #path('hello_world/', hello_world, name='hello_world'),
    
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'), #로그인 view는 따로 템플릿 설정. 괄호 위치 주의. 
    path('logout/', LogoutView.as_view(), name='logout'), #로그아웃 뷰는 없어도 됨.
    
    path('create/', AccountCreateView.as_view(), name='create'), #class형 view는 이후에 .as_view()를 적어야 한다.
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'), #<int:pk>는 접속 사용자 각각의 개별 구별자이다 (primary key)
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include, reverse #include 추가
#미디어 라우팅을 위한 import 
from django.conf.urls.static import static #static 안의 static이다
from django.conf import settings
from articleapp.views import ArticleListView

urlpatterns = [
    path('', ArticleListView.as_view(), name='home'),
    
    path('admin/', admin.site.urls),
    path('accounts/',include('accountapp.urls')), # ,까지 
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('subscribes/', include('subscribeapp.urls')),
    #소셜 로그인 앱
    path('socialauth/', include('socialauth.urls')),
    path('social-auth/', include('social_django.urls', namespace="social")), #이건 꼭 최상위 urls.py에 써줘야 한다.
    #allauth
    path('accounts/', include('allauth.urls')),
    
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/commentapp/urls.py
from django.urls import path, include
from commentapp.views import *

app_name = 'commentapp'

urlpatterns = [
    path('create/', CommentCreateView.as_view(), name='create'),
    path('delete/<int:pk>', CommentDeleteView.as_view(), name='delete'),
    path('anonymouscreate/', AnonymousCommentCreateView.as_view(), name='anonymouscreate'),
    path('anonymousdelete/<int:pk>', AnonymousCommentDeleteView.as_view(), name='anonymousdelete'),
]

blog/commentapp/models.py
from django.db import models
from articleapp.models import Article
from django.contrib.auth.models import User
# Create your models here.


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, null=True, related_name='comment') #Article 객체를 사용할 수 있게 연결, 글 삭제 시 댓글 db도 삭제되개.
    writer = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='comment')
    content = models.TextField(null=False) #댓글은 무조건 뭐라도 작성 필요
    created_at = models.DateTimeField(auto_now=True)
    

    
#익명 댓글 기능 작성하기 related_name은 foreignKey를 사용한 곳애만 사용해야 한다.
class AnonymousComment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, null=False, related_name='anonymouscomment')
    writer = models.CharField(max_length=15, null=False)
    password = models.CharField(max_length=12, null=False)
    content = models.TextField(null=False)
    created_at = models.DateTimeField(auto_now=True)
    
#model, form 만들고 migrate하기 

blog/commentapp/forms.py
from commentapp.models import *
from django.forms import ModelForm
from django import forms

class CommentCreationForm(ModelForm):
    # WYSIWYG 적용 
    content = forms.CharField(widget=forms.Textarea(attrs={'class' : 'editable', #내장 CharField의 여러 속성들을 변경한다. text-left는 부트스트랩 class css이다
                                                          'style' : 'height: auto; text-align: left; border: 1px solid rgb(206,212,218);'  }))
    class Meta:
        model = Comment
        fields = ['content']
        
        

class AnonymousCommentCreationForm(ModelForm):
    content = forms.CharField(widget=forms.Textarea(attrs={'class' : 'editable form-control',
                                                          'style' : 'height:auto; text-align: left; border: 1px solid rgb(206,212,218);' }))
    
    class Meta:
        model = AnonymousComment
        fields = ['writer', 'password', 'content']
        
        widgets = {
            'writer' : forms.TextInput(
                attrs = {
                    'class' : 'form-control ml-2',
                    'placeholder' : "이름"
                }
            ),
            
            'password' : forms.TextInput(
                attrs = {
                    'class' : 'form-control ml-2',
                    'placeholder' : "비밀번호"
                }
            )
        }
        

            

#model, form 만들고 migration하기
        

blog/commentapp/views.py
from django.shortcuts import render
from commentapp.models import *
from commentapp.forms import *
from django.urls import reverse_lazy
from django.views.generic import * #CreateView, DeleteView

from articleapp.models import Article

from django.utils.decorators import method_decorator
from commentapp.decorators import *
# Create your views here.



class CommentCreateView(CreateView):
    model = Comment
    form_class = CommentCreationForm
    template_name = 'commentapp/create.html'
    
    def form_valid(self,form):
        temp_comment = form.save(commit=False)
        temp_comment.article = Article.objects.get(pk=self.request.POST['article_pk']) # input hidden으로 보낸 article_pk
        temp_comment.writer = self.request.user
        temp_comment.save()
        return super().form_valid(form)
    
    def get_success_url(self): 
        return reverse_lazy('articleapp:detail', kwargs={'pk':self.object.article.pk}) #self.object는 comment이다
    
    
    
@method_decorator(comment_ownership_required, 'get')
@method_decorator(comment_ownership_required, 'post')
class CommentDeleteView(DeleteView):
    model = Comment
    context_object_name = 'target_comment'
    template_name = 'commentapp/delete.html'

    def get_success_url(self): 
        return reverse_lazy('articleapp:detail', kwargs={'pk':self.object.article.pk})

    

# 익명 댓글 Views
class AnonymousCommentCreateView(CreateView):
    model = AnonymousComment
    form_class = AnonymousCommentCreationForm
    template_name = 'commentapp/anonymouscreate.html' #추후 위의 create.html과 login 상태 확인하여 다르게 표시하는 형태로 통합할 것

    def form_valid(self,form):
        temp_comment = form.save(commit=False)
        temp_comment.article = Article.objects.get(pk=self.request.POST['article_pk']) # input hidden으로 보낸 article_pk
        temp_comment.writer = self.request.POST['writer']
        temp_comment.password = self.request.POST['password']
        temp_comment.save()
        return super().form_valid(form)
    
    
    def get_success_url(self):
        return reverse_lazy('articleapp:detail', kwargs={'pk' : self.object.article.pk })
    
    
class AnonymousCommentDeleteView(DeleteView):
    model = AnonymousComment
    context_object_name = 'target_comment'
    template_name = 'commentapp/anonymousdelete.html'
    
    def get_context_data(self, **kwargs):
        object_list = AnonymousComment.objects.get(pk=self.object.pk).password
        #print("target_object: ", object_list)
        return super(AnonymousCommentDeleteView,self).get_context_data(target_comment_pw=object_list,**kwargs)
    
    
    def get_success_url(self): 
        return reverse_lazy('articleapp:detail', kwargs={'pk':self.object.article.pk})

blog/commentapp/templates/commentapp/anonycreatebackup.html
<!-- 이전 버전(23.02.13이전)의 일반 bootstrap 사용한 form이다 -->


<!-- extends base.html 없다 (이건 include되는 것이기 때문) -->
{% load bootstrap4 %}

{% block content %}
<!-- WYSIWYG -->
<script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">

<style>
.medium-editor-element {
    word-wrap: break-word;
    min-height: 100px;
}
</style> <!-- 내장 스타일 오버라이딩-->


	<div style="text-align:center; max-width:500px; margin:4rem auto;">
        <div class="mb-4">
            <h4>익명 Comment</h4>
            <h6 style="color:grey; font-size:x-small;">로그인하면 해당 계정으로 댓글 작성이 가능합니다.</h6>
        </div>
        <form action="{% url 'commentapp:anonymouscreate' %}" method="post">
            {% csrf_token %}
            <!--{{ form }}--> <!--views.py의 AccountCreateview 클래스의 UserCreationForm을 그대로 불러온다.-->
            {% bootstrap_form form %}
            
            
            <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3" value="저장">
            <input type="hidden" name="article_pk" value="{{ article.pk }}"> <!-- article을 articleapp의 detail.html에서 with로 보내줬다-->
        </form>
    </div>

<script>var editor = new MediumEditor('.editable');</script>
{% endblock %}

blog/commentapp/templates/commentapp/anonymouscreate.html
<!-- extends base.html 없다 (이건 include되는 것이기 때문) -->
{% load bootstrap4 %}

{% block content %}
<!-- WYSIWYG -->
<script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">

<style>
.medium-editor-element {
    word-wrap: break-word;
    min-height: 100px;
}
    
    @media screen and (max-width:600px){
        input[type="text"]{
            width: 9.2rem;
        }
                                
    }

    
</style> <!-- 내장 스타일 오버라이딩-->



<!--뉴 댓글 작성란 시작-->
<!-- https://sang12.co.kr/176/BootStrap4-%EB%8C%93%EA%B8%80%EC%B0%BD%28reply%29-%EB%A7%8C%EB%93%A4%EA%B8%B0-%231 -->
<form action="{% url 'commentapp:anonymouscreate' %}" method="post">
    {% csrf_token %}
    <div class="card mb-2">
        <div class="card-header bg-light">
        <i class="fa fa-comment fa"></i> leave comments
        </div>
        <div class="card-body">
            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                <div class="form-inline mb-2">
                    <label for="replyId"><i class="fa fa-user-circle-o fa-2x"></i></label>
                    {{ form.writer }}
                    <label for="replyPassword" class="ml-4"><i class="fa fa-unlock-alt fa-2x"></i></label>
                    {{ form.password }}
                </div>
                    {{ form.content }}
                <button type="submit" class="btn btn-dark mt-3">Post</button>
                <input type="hidden" name="article_pk" value="{{ article.pk }}"> <!-- article을 articleapp의 detail.html에서 with로 보내줬다-->
                </li>
            </ul>
        </div>
    </div>
</form>




<script>var editor = new MediumEditor('.editable');</script>
{% endblock %}

blog/commentapp/templates/commentapp/anonymousdelete.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

<script>
    var isvalid = false;
    var password_check = function() {
        const user_input = document.getElementById("input_pw").value;
        console.log(user_input);
        if(user_input === "{{ target_comment_pw }}" ){ // 쌍따옴표 넣어야 한다. 괄호 내부는 그대로 치환한다
            document.getElementById('checkform').style.display = "block";
            isvalid = true;
        }
        else{
            alert("비밀번호가 틀립니다.")
        }
    
    }
    
    function checkForm(){
        let f = document.deleteform;
        if(isvalid){
            return true
        }else{
            alert('올바른 접근이 아닙니다.');
            return false;
        }
    }

</script>


	<div style="text-align:center; max-width:500px; margin:4rem auto;">
        <div class="mb-4">
            <h4>삭제 : {{ target_comment.content | safe }}</h4>
        </div>
        <input type="password" id="input_pw" placeholder="Password" style="width:200px; text-align:center;">
        <input type="button" onclick="password_check()" class="btn btn-secondary" value="check">
        
        <div id="checkform" style="display:none;">
            <form name="deleteform" onsubmit="return checkForm()" action="{% url 'commentapp:anonymousdelete' pk=target_comment.pk %}" method="post">
                {% csrf_token %}
                <input type="submit" class="btn btn-danger rounded-pill col-6 mt-3" value="삭제">
            </form>
        </div>
        
    </div>
{% endblock %}

blog/commentapp/templates/commentapp/create.html
<!-- extends base.html 없다 (이건 include되는 것이기 때문) -->
{% load bootstrap4 %}
{% load static %}
{% block content %}
<!-- WYSIWYG -->
<script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">

<style>
.medium-editor-element {
    word-wrap: break-word;
    min-height: 100px;
}
    
    
    .card img {
        border-radius : 10rem;
        width:3rem;
        height:3rem;
    }
    
    
    
</style> <!-- 내장 스타일 오버라이딩-->

<!--뉴 댓글 작성란 시작-->
<!-- https://sang12.co.kr/176/BootStrap4-%EB%8C%93%EA%B8%80%EC%B0%BD%28reply%29-%EB%A7%8C%EB%93%A4%EA%B8%B0-%231 -->
<form action="{% url 'commentapp:create' %}" method="post">
    {% csrf_token %}
    <div class="card mb-2">
        <div class="card-header bg-light">
        <i class="fa fa-comment fa"></i> leave comments
        </div>
        <div class="card-body">
            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                <div class="form-inline mb-2">
                    <label for="replyId">
                        {% if user.profile %}
                        <img src="{{ user.profile.image.url }}">
                        {% else %}
                        <img src="{% static 'icons/noprofileimage.png'}">
                        {% endif %}
                    </label>
                    <span style="margin-left : 1rem; font-size: 1.5rem;">{{ user }}</span>
                </div>
                    {{ form.content }}
                <button type="submit" class="btn btn-dark mt-3">Post</button>
                <input type="hidden" name="article_pk" value="{{ article.pk }}"> <!-- article을 articleapp의 detail.html에서 with로 보내줬다-->
                </li>
            </ul>
        </div>
    </div>
</form>

<script>var editor = new MediumEditor('.editable');</script>
{% endblock %}

blog/commentapp/templates/commentapp/createbackup.html
<!-- extends base.html 없다 (이건 include되는 것이기 때문) -->
{% load bootstrap4 %}

{% block content %}
<!-- WYSIWYG -->
<script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">

<style>
.medium-editor-element {
    word-wrap: break-word;
    min-height: 100px;
}
</style> <!-- 내장 스타일 오버라이딩-->


	<div style="text-align:center; max-width:500px; margin:4rem auto;">
        <div class="mb-4">
            <h4>Comment</h4>
        </div>
        <form action="{% url 'commentapp:create' %}" method="post">
            {% csrf_token %}
            <!--{{ form }}--> <!--views.py의 AccountCreateview 클래스의 UserCreationForm을 그대로 불러온다.-->
            {% bootstrap_form form %}
            
            
            {% if user.is_authenticated %}
            <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3" value="저장">
            {% else %}
            <a href="{% url 'accountapp:login' %}?next={{ request.path }}"  class="btn btn-dark rounded-pill col-6 mt-3">로그인</a> <!-- 로그인하면 다시 돌아오게-->
            {% endif %}
            <input type="hidden" name="article_pk" value="{{ article.pk }}"> <!-- article을 articleapp의 detail.html에서 with로 보내줬다-->
        </form>
    </div>

<script>var editor = new MediumEditor('.editable');</script>
{% endblock %}

blog/commentapp/templates/commentapp/delete.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
	<div style="text-align:center; max-width:500px; margin:4rem auto;">
        <div class="mb-4">
            <h4>삭제 : {{ target_comment.content | safe }}</h4>
        </div>
        <form action="{% url 'commentapp:delete' pk=target_comment.pk %}" method="post">
            {% csrf_token %}
            <input type="submit" class="btn btn-danger rounded-pill col-6 mt-3" value="삭제">
        </form>
    </div>
{% endblock %}

blog/commentapp/templates/commentapp/detail.html
{% load static %}

<style>
    .d-flex img {
            border-radius : 10rem;
            width:3rem;
            height:3rem;
        }
</style>

<div class="d-flex">
    <div class="flex-fill">
        <div class="card mt-2">
            <div class="card-header">
                <table>
                    <tr class="align-middle">
                        {% if comment.writer.username %}
                            {% if comment.writer.profile %}
                        <td rowspan="2" class="pr-2"><img src="{{ comment.writer.profile.image.url }}"></td>
                        <td class="ml" style="text-align: left;">{{ comment.writer.profile.nickname }}</td>
                            {% else %}
                        <td rowspan="2" class="pr-2"><i class="fa fa-user-o fa-2x"></i></td>
                        <td class="ml" style="text-align: left;">{{ comment.writer.username }}</td>
                            {% endif %}
                        {% else %}sdsd
                        <td rowspan="2" class="pr-2"><i class="fa fa-user-o fa-2x"></i></td>
                        <td class="ml" style="text-align: left;">{{ comment.writer }}</td>
                        {% endif %}
                    </tr>
                    <tr>
                        <td>
                            <font size="2">{{ comment.created_at }}</font> 

                        </td>
                    </tr>
                </table>
            </div>
            <div class="card-body" style="text-align: left;">
                <p class="card-text">{{ comment.content | safe }}</p>
        
                
            
                {% if comment.writer.username %}
        {% if comment.writer == user %}
        <div style="text-align: right;">
            <a href="{% url 'commentapp:delete' pk=comment.pk %}" class="btn btn-danger">삭제</a> <!-- url 'app:#'  쓰려면 urls.py에 추가하기-->
        </div>
        {% endif %}
    {% else %}
        <!-- 익명 댓글일 경우 -->
        <div style="text-align: right;">
            <a href="{% url 'commentapp:anonymousdelete' pk=comment.pk %}" class="btn btn-danger">삭제</a> <!-- url 'app:#'  쓰려면 urls.py에 추가하기-->
        </div>
    {% endif %}
                
                
                

            </div>
        </div>
    </div>
</div>

blog/commentapp/templates/commentapp/detailbackup.html
{% load static %}
<div style="border:1px solid;
            text-align:left;
            padding:4%;
            margin:1rem 0;
            border-radius: 1rem;
            border-color: #bbb;">
    <div>
        <!-- 로그인된 사용자의 댓글일 경우 -->
        {% if comment.writer.profile %}
            <div style="object-fit:cover; width:10%; float:left; margin-right: 0.5rem; margin-bottom:0.5rem;">
                    {% if comment.writer.profile.image %}
                    <img src="{{ comment.writer.profile.image.url }}" style="border-radius:10rem; width:100%; height:100%;">
                    {% else %}
                    <img src="{% static 'icons/noprofileimage.png' %}" style="border-radius:10rem; width:100%; height: 100%;">
                    {% endif %}
                </div>
            <strong>{{ comment.writer.profile.nickname }}</strong>
            <br> <!-- 자동 줄바꿈을 막기 위해 작성하는 특수공백문자 &nbsp&nbsp&nbsp-->
            {{ comment.created_at }}
        
        {% else %}
        <!-- 익명 댓글일 경우-->
        <div style="object-fit:cover; width:10%; float:left; margin-right: 0.5rem; margin-bottom:0.5rem;">
                    <img src="{% static 'icons/noprofileimage.png' %}" style="border-radius:10rem; width:100%; height: 100%;">
                </div>
            <!-- profile이 없으나 로그인된 계정이라 id가 있을 경우 -->
            {% if coment.writer.username %}
                <strong>{{ comment.writer.username }}</strong>
                <br> 
            {% else %}
                <strong>{{ comment.writer }}</strong>
                <br> 
            {% endif %}
            {{ comment.created_at }}
        {% endif %}
    </div>
    
    
    
    <div style="margin: 1rem 0;">
        {{ comment.content | safe }} <!-- safe 적어야 html태그는 제외되고 plain text만 표시-->
    </div>
    
    <!-- 로그인된 사용자의 댓글일 경우 -->
    <!-- articleapp/detail.html에서 일반/익명 댓글 모두 comment라는 인자로 넘겨준다.-->
    <!-- comment.writer.username이 존재하면 일반 유저의 댓글, 없으면 익명 댓글로 취급-->
    {% if comment.writer.username %}
        {% if comment.writer == user %}
        <div style="text-align: right;">
            <a href="{% url 'commentapp:delete' pk=comment.pk %}" class="btn btn-danger">삭제</a> <!-- url 'app:#'  쓰려면 urls.py에 추가하기-->
        </div>
        {% endif %}
    {% else %}
        <!-- 익명 댓글일 경우 -->
        <div style="text-align: right;">
            <a href="{% url 'commentapp:anonymousdelete' pk=comment.pk %}" class="btn btn-danger">삭제</a> <!-- url 'app:#'  쓰려면 urls.py에 추가하기-->
        </div>
    {% endif %}

    
</div>