blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include, reverse #include 추가
#미디어 라우팅을 위한 import 
from django.conf.urls.static import static #static 안의 static이다
from django.conf import settings
from articleapp.views import ArticleListView

urlpatterns = [
    path('', ArticleListView.as_view(), name='home'),
    
    path('admin/', admin.site.urls),
    path('accounts/',include('accountapp.urls')), # ,까지 
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('subscribes/', include('subscribeapp.urls')),
    #소셜 로그인 앱
    path('socialauth/', include('socialauth.urls')),
    path('social-auth/', include('social_django.urls', namespace="social")), #이건 꼭 최상위 urls.py에 써줘야 한다.
    #allauth
    path('accounts/', include('allauth.urls')),
    
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/projectapp/urls.py
from django.urls import include, path
from projectapp.views import *


app_name = 'projectapp'

urlpatterns=[
    path('list/', ProjectListView.as_view(), name='list'),
    path('detail/<int:pk>', ProjectDetailView.as_view(), name='detail'),
    path('create/', ProjectCreateView.as_view(), name='create'),
    path('delete/<int:pk>', ProjectDeleteView.as_view(), name='delete'),
    path('update/<int:pk>', ProjectUpdateView.as_view(), name='update'),
]
    

blog/subscribeapp/urls.py
from articleapp.views import *
from django.urls import path
from django.views.generic import TemplateView #django 기본 제공 view이다. 
from subscribeapp.views import SubscriptionView

app_name='subscribeapp'


urlpatterns = [
    path('subscribe/',SubscriptionView.as_view(), name='subscribe')
    
]

blog/articleapp/models.py
from django.db import models
from django.contrib.auth.models import User
from projectapp.models import Project
from tinymce.models import HTMLField #tinymce은 htmlfield를 쓴다
# Create your models here.



class Article(models.Model):
    writer = models.ForeignKey(User, on_delete=models.CASCADE, related_name='article', null=True) #탈퇴 시 게시글이 사라지지 않고 게시글 작성자(writer)를 NULL로 변환 #set_NULL이라서 null=True도 해줘야 한다 
    #230118 큰일난다 제발 CASCADE해라
    project = models.ForeignKey(Project, on_delete=models.SET_NULL, related_name='article', null=True) #Projectapp과 연결
    title = models.CharField(max_length=200, null=True, blank=False)
    image = models.ImageField(upload_to='article/',null=True, blank=True) #media/article에 저장된다. 안 올려도 되도록 하려면 왠지는 모르겠는데 blank=True도 필요.
    content = HTMLField(null=True, blank=False)
    #content = models.TextField(null=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)
    
    #모델을 바꾸면 migration을 다시 해야 한다.
    

blog/projectapp/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Project(models.Model):
    writer = models.ForeignKey(User, on_delete=models.CASCADE, related_name='project', null=True)
    #해당 user가 탈퇴하면 해당 user의 project는 모두 삭제된다.
    title = models.CharField(max_length=30, null=False)
    description = models.TextField(max_length=200, null=True)
    image = models.ImageField(upload_to='project/', null=False)
    created_at = models.DateField(auto_now_add=True, null=True)
    
    
    def __str__(self):
        return f'{self.pk} : {self.title}' #article create의 project select에서 표시되는 이름을 pk : title 로 변경

blog/projectapp/forms.py
from django.forms import ModelForm
from projectapp.models import *

class ProjectCreationForm(ModelForm):
    class Meta:
        model = Project
        fields = ['image','title','description'] #순서대로 위쪽부터 나옴
        #model, form 만들면 migration 하기 이후 view 만들기

blog/projectapp/views.py
from django.shortcuts import render
from django.views.generic import CreateView, DetailView, ListView, DeleteView, UpdateView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from projectapp.forms import *
from django.urls import reverse_lazy
from django.views.generic.list import MultipleObjectMixin
from articleapp.models import Article
from subscribeapp.models import Subscription
from django.utils.decorators import method_decorator
from projectapp.decorators import project_ownership_required

# Create your views here.
@method_decorator(login_required,'get')
@method_decorator(login_required,'post')
class ProjectCreateView(CreateView):
    model = Project
    form_class = ProjectCreationForm
    template_name = 'projectapp/create.html'
    
    
    def get_success_url(self):
        return reverse_lazy('projectapp:detail', kwargs={'pk' : self.object.pk})
    
#DeleteView가 작동하지 않았던 이유가 writer를 만들어놓고 form_valid로 지정을 안 해줘서 그런 것이었다.
    def form_valid(self,form):
        temp_project = form.save(commit=False)
        temp_project.writer = self.request.user
        temp_project.save()
        return super().form_valid(form)
    
    
class ProjectDetailView(DetailView, MultipleObjectMixin): #믹스인 사용
    model = Project
    context_object_name = 'target_project'
    template_name = 'projectapp/detail.html'
    
    def get_context_data(self, **kwargs): #템플릿에게 데이터를 전달하기 위해 오버라이딩
        project = self.object
        user = self.request.user
        
        if user.is_authenticated:
            subscription = Subscription.objects.filter(user=user,project=project)
        else:
            subscription = None
        object_list = Article.objects.filter(project=self.get_object()) #해당 project에 속해있는 articles를 가져오는 건데 이해는 잘 안 된다.
        ordered_list = Article.objects.order_by('-created_at')
        return super(ProjectDetailView,self).get_context_data(object_list=ordered_list,
                                                              subscription=subscription,
                                                              **kwargs)
                    #해당 project에 속해있는 articles, 접속한 유저의 해당 프로젝트의 구독 정보를 돌려준다
    
    
    
    
class ProjectListView(ListView):
    model = Project
    template_name = "projectapp/list.html"
    paginate_by = 25
    context_object_name = 'project_list'


@method_decorator(project_ownership_required, 'get')
@method_decorator(project_ownership_required, 'post')
class ProjectDeleteView(DeleteView):
    model = Project
    template_name = 'projectapp/delete.html'
    context_object_name = "target_project"
    success_url = reverse_lazy("projectapp:list")
    
    
    

@method_decorator(project_ownership_required, 'get')
@method_decorator(project_ownership_required, 'post')
class ProjectUpdateView(UpdateView):
    model = Project
    template_name = 'projectapp/update.html'
    form_class = ProjectCreationForm
    context_object_name = 'target_project'
    
    def get_success_url(self):
        return reverse_lazy('projectapp:detail', kwargs={'pk' : self.object.pk})
        
        
        
        
#View 만들면 제발 urls.py에 추가하자.............

blog/projectapp/templates/projectapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
<div style="text-align:center; max-width:500px; margin:4rem auto">
    <div class="mb-4">
        Project 만들기
    </div>
    <form action="{% url 'projectapp:create' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3" value="저장">
    </form>
</div>
{% endblock %}

blog/projectapp/templates/projectapp/delete.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
	<div style="text-align:center; max-width:500px; margin:4rem auto;">
        <div class="mb-4">
            <h4>삭제하기 : {{ target_project.title }}</h4>
        </div>
        <form action="{% url 'projectapp:delete' pk=target_project.pk %}" method="post">
            {% csrf_token %}
            <input type="submit" class="btn btn-danger rounded-pill col-6 mt-3" value="삭제">
        </form>
    </div>
{% endblock %}

blog/projectapp/templates/projectapp/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!-- 화면 표시 스타일 -->
<script type="application/javascript">
    function gridview(){
        document.getElementById('list').style.display = "none";
        document.getElementById('listselect').style.backgroundColor = "white";
        document.getElementById('grid').style.display = "block";
        document.getElementById('gridselect').style.backgroundColor = "#f2f2f2";
    }
    
    function listview(){
        document.getElementById('list').style.display = "block";
        document.getElementById('listselect').style.backgroundColor = "#f2f2f2";
        document.getElementById('grid').style.display = "none";
        document.getElementById('gridselect').style.backgroundColor = "white";
    }


</script>

<style>
    @media screen and (max-width:600px) {
        .container_list { 
            padding: 0;
            margin: 0 auto;
            display: none;
        }
        
        .container_list .list_div{
            padding: 0.5rem 1rem;
            position:relative;
        }
        
            
        .container_list img{
            width:100%;
            height:100%;
            object-fit:cover;
            border-radius:0.5rem;
        }
            
        .container_list .image_div{
            height:100%;
            width: 7rem;
            position:absolute;
            top: 0;
            right:1rem;
        }
            
        .container_list .contents_div{
            margin-top: 0.8rem;
            height: 100%;
            width: calc(100% - 7rem);
            font-size: x-small !important;
        }
        
        .container_list .contents_div p, .container_list .contents_div span{
            font-size: x-small !important;
        }
            
        
}
    /* pc를 위한 미디어 쿼리.. 추후 수정 */
    @media screen and (min-width:600px) {
        .container_list { 
            padding: 0;
            margin: 0 auto;
            display: none;
        }
        
        .container_list .list_div{
            padding: 0.5rem 1rem;
            position:relative;
        }
        
            
        .container_list img{
            width:100%;
            height:100%;
            object-fit:cover;
            border-radius:0.5rem;
        }
            
        .container_list .image_div{
            height:100%;
            width: 7rem;
            position:absolute;
            top: 0;
            right:1rem;
        }
            
        .container_list .contents_div{
            margin-top: 0.8rem;
            height: 100%;
            width: calc(100% - 7rem);
            font-size: x-small !important;
        }
        
        .container_list .contents_div p, .container_list .contents_div span{
            font-size: x-small !important;
        }
            
        
}
    


</style>




<!-- 프로젝트 정보 영역-->
<div style="text-align:center; max-width:500px; margin:4rem auto 2rem auto;">
    
    <img src="{{ target_project.image.url }}" alt="#" style="
                                                             height:12rem;
                                                             width:12rem;
                                                             border-radius:20rem;
                                                             margin-bottom:2rem;
                                                             object-fit:cover;">
    <h2 style="font-family:'NanumSqureB';">{{ target_project.title }}</h2>
    
    <h5 style="margin-bottom:1rem;">{{ target_project.description }}</h5>
    
    
    <!-- 구독 영역-->
    <div>
        {% if user.is_authenticated %}
            {% if not subscription %}
            <a class="btn btn-primary rounded-pill px-4"
               href="{% url 'subscribeapp:subscribe' %}?project_pk={{ target_project.pk }}">
                Subscribe
            </a>
            {% else %}
            <a class="btn btn-dark rounded-pill px-4"
               href="{% url 'subscribeapp:subscribe' %}?project_pk={{ target_project.pk }}">
            Unsubscribe
            </a>
            {% endif %}
        {% endif %}
    </div>
</div>
    

{% if user.is_authenticated %}
<!-- 삭제 버튼 -->
<div class="text-center mb-5">
    <a class="btn btn-info rounded-pill px-4"
               href="{% url 'projectapp:update' pk=target_project.pk %}">
                수정
    </a>
    <a class="btn btn-danger rounded-pill px-4"
               href="{% url 'projectapp:delete' pk=target_project.pk %}">
                삭제
    </a>
</div>
{% endif %}




    
<!-- 게시글 영역-->
<div>
    {% include 'list.html' with article_list=object_list %}
</div>
    
   

{% endblock %}

blog/projectapp/templates/projectapp/detailbackup.html
{% extends 'base.html' %}

{% block content %}

<!-- 화면 표시 스타일 -->
<script type="application/javascript">
    function gridview(){
        document.getElementById('list').style.display = "none";
        document.getElementById('listselect').style.backgroundColor = "white";
        document.getElementById('grid').style.display = "block";
        document.getElementById('gridselect').style.backgroundColor = "#f2f2f2";
    }
    
    function listview(){
        document.getElementById('list').style.display = "block";
        document.getElementById('listselect').style.backgroundColor = "#f2f2f2";
        document.getElementById('grid').style.display = "none";
        document.getElementById('gridselect').style.backgroundColor = "white";
    }


</script>

<style>
    @media screen and (max-width:600px) {
        .container_list { 
            padding: 0;
            margin: 0 auto;
            display: none;
        }
        
        .container_list .list_div{
            padding: 0.5rem 1rem;
            position:relative;
        }
        
            
        .container_list img{
            width:100%;
            height:100%;
            object-fit:cover;
            border-radius:0.5rem;
        }
            
        .container_list .image_div{
            height:100%;
            width: 7rem;
            position:absolute;
            top: 0;
            right:1rem;
        }
            
        .container_list .contents_div{
            margin-top: 0.8rem;
            height: 100%;
            width: calc(100% - 7rem);
            font-size: x-small !important;
        }
        
        .container_list .contents_div p, .container_list .contents_div span{
            font-size: x-small !important;
        }
            
        
}
    /* pc를 위한 미디어 쿼리.. 추후 수정 */
    @media screen and (min-width:600px) {
        .container_list { 
            padding: 0;
            margin: 0 auto;
            display: none;
        }
        
        .container_list .list_div{
            padding: 0.5rem 1rem;
            position:relative;
        }
        
            
        .container_list img{
            width:100%;
            height:100%;
            object-fit:cover;
            border-radius:0.5rem;
        }
            
        .container_list .image_div{
            height:100%;
            width: 7rem;
            position:absolute;
            top: 0;
            right:1rem;
        }
            
        .container_list .contents_div{
            margin-top: 0.8rem;
            height: 100%;
            width: calc(100% - 7rem);
            font-size: x-small !important;
        }
        
        .container_list .contents_div p, .container_list .contents_div span{
            font-size: x-small !important;
        }
            
        
}
    


</style>




<!-- 프로젝트 정보 영역-->
<div style="text-align:center; max-width:500px; margin:4rem auto 2rem auto;">
    
    <img src="{{ target_project.image.url }}" alt="#" style="
                                                             height:12rem;
                                                             width:12rem;
                                                             border-radius:20rem;
                                                             margin-bottom:2rem;
                                                             object-fit:cover;">
    <h2 style="font-family:'NanumSqureB';">{{ target_project.title }}</h2>
    
    <h5 style="margin-bottom:1rem;">{{ target_project.description }}</h5>
    
    
    <!-- 구독 영역-->
    <div>
        {% if user.is_authenticated %}
            {% if not subscription %}
            <a class="btn btn-primary rounded-pill px-4"
               href="{% url 'subscribeapp:subscribe' %}?project_pk={{ target_project.pk }}">
                Subscribe
            </a>
            {% else %}
            <a class="btn btn-dark rounded-pill px-4"
               href="{% url 'subscribeapp:subscribe' %}?project_pk={{ target_project.pk }}">
            Unsubscribe
            </a>
            {% endif %}
        {% endif %}
    </div>
</div>
    

{% if user.is_authenticated %}
<!-- 삭제 버튼 -->
<div class="text-center mb-5">
    <a class="btn btn-info rounded-pill px-4"
               href="{% url 'projectapp:update' pk=target_project.pk %}">
                수정
    </a>
    <a class="btn btn-danger rounded-pill px-4"
               href="{% url 'projectapp:delete' pk=target_project.pk %}">
                삭제
    </a>
</div>
{% endif %}




    
<!-- 게시글 영역-->
<div>
    {% include 'snippets/article_list_viewselect.html' with article_list=object_list %}
</div>
    
   

{% endblock %}

blog/projectapp/templates/projectapp/list.html
{% extends 'base.html' %}
{% load static %} <!-- static 쓰려면 꼭 해줘야 함-->

{% block content %}
    <style>
        
        .container {
            padding: 0;
            margin:0, auto;
        }
        
        
        /* .container a{
            width: 45%;
            max-width: 250px;
        } 스타일은 articleapp의 list.html에서 가져온다. 하지만 이 스타일에서는 고정된 너비를 사용
        원래 a태그 안에 이미지가 있으나 이제는 이미지 크기를 직접 조정
        */
        
        .container div {
          justify-content: center;
          align-items: center;
          border-radius: 1rem;
        }
        
        .container img {
            width:7rem;
            height:7rem;
            object-fit:cover;
            border-radius:1rem;
        }
        
    </style>
    {% if project_list %} <!--project_list가 존재한다면-->
    <div class="container">
        {% for project in project_list %} <!-- view에서 context_object_name이다-->    
        <a href="{% url 'projectapp:detail' pk=project.pk %}">
            {% include 'snippets/project_card.html' with project=project %} <!-- for문에 썼던 변수를 전달하기 위함(전달할 이름 = 전달할 내용)-->
        </a>
        {% endfor %}
    </div>
     <script src="{% static 'js/magicgrid.js' %}"></script> <!-- container라는 클래스를 js에서 사용하므로 안에다가 넣어준다-->
    {% else %}
    <div style="text-align:center;">
        <h1>
            게시글이 존재하지 않습니다.
        </h1>    
    </div>
    {% endif %}
    
    <!-- pagination 영역 -->
    {% include 'snippets/pagination.html' with page_obj=page_obj %}
    

    <div style="text-align:center;">
        <a href="{% url 'projectapp:create' %}" class="btn btn-dark rounded-pill px-3 mt-3 mb-3">
        새 게시판 만들기
        </a>
    </div>







{% endblock %}

blog/projectapp/templates/projectapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
<div style="text-align:center; max-width:500px; margin:4rem auto">
    <div class="mb-4">
        게시판 수정하기
    </div>
    <!-- form action에 pk 안 적어주면 noreverseMatch 오류가 난다 -->
    <form action="{% url 'projectapp:update' pk=target_project.pk %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3" value="저장">
    </form>
</div>
{% endblock %}