blog/accountapp/urls.py
from django.contrib import admin
from django.urls import path, include #include 추가
from accountapp.views import * #views.py의 funtion, class view들을 불러온다
from django.contrib.auth.views import LoginView, LogoutView  #django 내장 Login/Logout View를 불러온다.

#urls.path(route, view, kwrags=None, name=None,Pattern=)

app_name='accountapp' #하면 좋음. 계속 쳐야 하니 그냥 이름 변수에 저장


urlpatterns = [
    #path('hello_world/', hello_world, name='hello_world'),
    
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'), #로그인 view는 따로 템플릿 설정. 괄호 위치 주의. 
    path('logout/', LogoutView.as_view(), name='logout'), #로그아웃 뷰는 없어도 됨.
    
    path('create/', AccountCreateView.as_view(), name='create'), #class형 view는 이후에 .as_view()를 적어야 한다.
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'), #<int:pk>는 접속 사용자 각각의 개별 구별자이다 (primary key)
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include, reverse #include 추가
#미디어 라우팅을 위한 import 
from django.conf.urls.static import static #static 안의 static이다
from django.conf import settings
from articleapp.views import ArticleListView

urlpatterns = [
    path('', ArticleListView.as_view(), name='home'),
    
    path('admin/', admin.site.urls),
    path('accounts/',include('accountapp.urls')), # ,까지 
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('subscribes/', include('subscribeapp.urls')),
    #소셜 로그인 앱
    path('socialauth/', include('socialauth.urls')),
    path('social-auth/', include('social_django.urls', namespace="social")), #이건 꼭 최상위 urls.py에 써줘야 한다.
    #allauth
    path('accounts/', include('allauth.urls')),
    
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/profileapp/urls.py
from profileapp.views import *
from django.urls import path

app_name='profileapp'


urlpatterns = [
    path('create/', ProfileCreateView.as_view(), name='create'),
    path('update/<int:pk>', ProfileUpdateView.as_view(), name='update'),
        path('list/', ProfileListView.as_view(), name='list'),

]

blog/accountapp/models.py
from django.db import models

# Create your models here.
# 모덷 클래스를 작성하고 나서 python manage.py makemigrations을 해야 blog/migrations에 새로운 .py가 생긴다.
# 이후 python manage.py migrate를 실행한다. 그러면 자동으로 db와 연동이 된다.
# blog/migrations 안의 파일은 삭제하는 다른 방법이 있으니 임의로 삭제하지 말자




# class HelloWorld(models.Model): #HelloWorld 객체는 text 멤버변수를 가지고 있다.
#     text = models.CharField(max_length=255, null=False)



#user는 다음과 같이 정의되어 있다
# class User(AbstractUser):
#     class Meta(AbstractUser.Meta):
#         swappable = 'AUTH_USER_MODEL'
#         username = models.CharField()
#         first_name = models.CharField()
#         last_name = models.CharField()
#         email = models.EmailField()
#         is_staff = models.BooleanField()
#         is_active = models.BooleanField()
#         date_joined = models.DateTimeField()

blog/articleapp/models.py
from django.db import models
from django.contrib.auth.models import User
from projectapp.models import Project
from tinymce.models import HTMLField #tinymce은 htmlfield를 쓴다
# Create your models here.



class Article(models.Model):
    writer = models.ForeignKey(User, on_delete=models.CASCADE, related_name='article', null=True) #탈퇴 시 게시글이 사라지지 않고 게시글 작성자(writer)를 NULL로 변환 #set_NULL이라서 null=True도 해줘야 한다 
    #230118 큰일난다 제발 CASCADE해라
    project = models.ForeignKey(Project, on_delete=models.SET_NULL, related_name='article', null=True) #Projectapp과 연결
    title = models.CharField(max_length=200, null=True, blank=False)
    image = models.ImageField(upload_to='article/',null=True, blank=True) #media/article에 저장된다. 안 올려도 되도록 하려면 왠지는 모르겠는데 blank=True도 필요.
    content = HTMLField(null=True, blank=False)
    #content = models.TextField(null=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)
    
    #모델을 바꾸면 migration을 다시 해야 한다.
    

blog/accountapp/forms.py
from django.contrib.auth.forms import UserCreationForm


class AccountUpdateForm(UserCreationForm):  #UserCreationForm을 상속받는다
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        self.fields['username'].disabled = True #이거만 없으면 UserCreationForm과 완전 동일하다

blog/accountapp/views.py
from django.shortcuts import render
from django.http import HttpResponse #추가해야 한다
from django.http import HttpResponseRedirect #이것도 따로 해야 한다..
from django.http import HttpResponseForbidden
from django.urls import reverse, reverse_lazy


# 모델도 import해야 한다.
#from accountapp.models import HelloWorld

# CRUD View class 이용한 CreateView 만들기
from django.views.generic import *  #CreateView, DetailView 등 불러오기
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


# UpdateView에서 수정된 form_class를 적용하기 위해 불러옴. 기본 경로는 blog이기 때문에 accountapp.forms이다.
from accountapp.forms import AccountUpdateForm


#decorator import
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from accountapp.decorators import *

# Create your views here. 

# decorator 배열
has_ownership=[login_required,account_ownership_required]

#MultipleObjectMixin
from django.views.generic.list import MultipleObjectMixin
from articleapp.models import Article


# @login_required #모듈을 통해 불러온다
# def hello_world(request):
    
#     # 로그인 인증
#    	#return HttpResponse("hello world!") #HttpResponse를 직접 리턴
#         #form의 method 값 get/post 따라서 요청을 나눈다
#     if request.method=="POST":
#         temp = request.POST.get('hello_world_input') #request의 post 요청 (하지만 대문자로 써야 한다)에서  input 태그의 name속성값이 hello_world_input인 것의 데이터를 가져와라


#         #DB에 저장하기 
#         new_hello_world = HelloWorld() #인스턴스 생성 (객체 타입은 HelloWorld이다)
#         new_hello_world.text = temp
#         new_hello_world.save() #DB에 new_hello_world 인스턴스를 저장

#         #DB에서 불러오기

#         hello_world_list = HelloWorld.objects.all() #HelloWorld 클래스 타입 내장 기본 함수여서 HelloWorld.을 쓰나보다?

#         return HttpResponseRedirect(reverse('accountapp:hello_world')) #/accountapp/urls.py의 app_name을 입력하면 알아서 urlpatterns의 경로를 참고하여 account/hello_world로 변환된다.


#         #return render(request, 'accountapp/hello_world.html', context={'hello_world_list': hello_world_list})
#     else:
#         hello_world_list = HelloWorld.objects.all()
#         return render(request, 'accountapp/hello_world.html', context={'hello_world_list': hello_world_list}) #/accountapp/hello_world가 아니다. 앞에 /는 꼭 빼야 한다 context는 보내줄 데이터다

    

    
    
class AccountCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy('accountapp:login') #reverse_lazy는 reverse와 같지만 reverse는 function에서, reverse_lazy는 class에서 사용한다.
    template_name = 'accountapp/create.html'
    
    
    
class AccountDetailView(DetailView,MultipleObjectMixin):
    model = User #U 대문자이다..
    context_object_name = 'target_user'
    template_name = 'accountapp/detail.html'
    
    paginate_by = 25
    
    def get_context_data(self, **kwargs):
        object_list = Article.objects.filter(writer=self.get_object()) #해당 project에 속해있는 articles를 가져오는 건데 이해는 잘 안 된다. Accountapp에서는 해당 account의 게시물이다.
        ordered_list = Article.objects.order_by('-created_at')
        return super(AccountDetailView,self).get_context_data(object_list=ordered_list,**kwargs)
    


    
@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')#클래스 안의 메서드에서 decorator를 사용하려면 이렇게 해야 한다. #사용자 정의 decorator (accountapp/decorators.py에 있음)
class AccountUpdateView(UpdateView):
    model = User
    context_object_name = 'target_user'
    form_class = AccountUpdateForm
    success_url = reverse_lazy('accountapp:detail') 
    template_name = 'accountapp/update.html'
    
    
        
        
    
    
@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountDeleteView(DeleteView): #CreateView, DetailView(Read이지만 장고에서는 Detail이다), DeleteView를 상속해서 기능이 추가된 새로운 뷰를 정의하는 것이다.
    model = User
    context_object_name = 'target_user'
    success_url = reverse_lazy('accountapp:login')
    template_name = 'accountapp/delete.html'
    
    
    
    
    
    
###################PROFILEAPP##########################
    

    
    
    
    
    
#처음 이렇게 만들고 root에서 setting.py에서 템플릿 경로 추가
#렌더링할 html경로를 적어주는 것
#여기서 만들고 최초 폴더의 urls.py에서 라우팅

# 1. 앱 만들기 (python manage.py startapp '앱 이름')
# 2. settings.py에 앱 추가
# 3. urls.py(프로젝트 폴더)에서 경로 지정
# 4. 앱 내부에 urls.py 만들기
# 5. 모델 만들기
# 6. form 만들기
# 7. python manage.py makemigrations 이후 python manage.py migrate를 해줘야 db와 연동이 된다.
# 8. View 만들기

# !! View 만드는 순서 : 
# 1. View.py에 class나 function 만들기 (template_name 등 추가)
# 2. urls.py에 path 추가하기
# 3. template 폴더에서 html 파일 작성하기

blog/accountapp/templates/accountapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}

{% block content %}
	<div style="text-align:center; max-width:500px; margin:4rem auto;">
        <div class="mb-4">
            <h4>Sign Up</h4>
        </div>
        <form action="{% url 'accountapp:create' %}" method="post">
            {% csrf_token %}
            <!--{{ form }}--> <!--views.py의 AccountCreateview 클래스의 UserCreationForm을 그대로 불러온다.-->
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3 mb-3" value="가입하기">
        </form>
        <h7>
                또는 소셜 계정으로 로그인
        </h7>
        {% include 'socialauth/login.html' %} <!-- include 구문은 자동으로 templates 폴더를 탐색하기 때문에 "include 앱 이릅/템플릿명"으로만 해도 작동한다.-->
        <h8 style="color:gray;">계정 정보는 SHA-256 단방향 암호화를 사용하여 저장되므로 그 누구도 본래의 비밀번호를 알 수 없습니다.</h8>
        <img src="{% static 'images/pwnotice.png' %}" alt="#">
    </div>
{% endblock %}

blog/accountapp/templates/accountapp/delete.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
	<div style="text-align:center; max-width:500px; margin:4rem auto;">
        <div class="mb-4">
            <h4>Quit</h4>
        </div>
        <form action="{% url 'accountapp:delete' pk=target_user.pk %}" method="post">
            {% csrf_token %}
            <input type="submit" class="btn btn-danger rounded-pill col-6 mt-3" value="탈퇴하기">
        </form>
    </div>
{% endblock %}

blog/accountapp/templates/accountapp/detail.html
{% extends 'base.html' %}

{% block content %}
<div class="dove_500px_div">
    <div>
        <p>
            {{ target_user.date_joined }}<span style="color:gray; font-size:x-small;">부터</span>
        </p>
        
        <!-- 프로파일 존재하면 닉네임 띄우고 아니면 프로파일 생성으로 유도-->
        {% if target_user.profile %}


        <!-- 이미지 넣기 -->
            <img src="{{ target_user.profile.image.url }}" alt="프로필 사진" style="width:12rem; height:12rem; border-radius:20rem; margin-bottom:2rem; object-fit:cover;"> 
            <!--이렇게 하고 urls.py(root의)에서 미디어 라우팅을 해야 사진이 제대로 뜸--> 

            <h2 style="font-family: 'NanumSqureB;">
                {{ target_user.profile.nickname }}
                {% if target_user == user %} <!--로그인된 사용자라면 보여주기 위해-->
            <a href="{% url 'profileapp:update' pk=target_user.profile.pk %}" class="material-icons" style="box-shadow:0 0 4px #ccc; border-radius:10rem; padding: .4rem;">
                    edit <!-- a태그 안의 내용에 따라서 아이콘의 종류가 바뀐다. 클래스는 material-icons 고정이다. 하위 요소에 태그는 없어야 한다.-->
            </a>
                {% endif %}

            </h2>
                    <!-- 한줄소개 표시-->
            <h5 style="margin-bottom:3rem;">
            {{ target_user.profile.message }}
            </h5>
        {% else %}

            {% if target_user == user %} <!--로그인된 사용자라면 보여주기 위해-->
                <a href="{% url 'profileapp:create' %}" class="btn btn-outline-info" style="margin: 1rem auto;display:block; width:50%;">
                    <h2 style="font-family: 'NanumSqureB;">
                    Create Profile
                </h2>
                </a>
        
            {% else %}
                <h2>
                작성된 소개가 없습니다.    
                </h2>
        
        
            {% endif %}


        {% endif %}
        

        
        {% if target_user == user %} <!-- target_user가 현재 접속한 user라면 (target_user는 views.py의 AccountDetailView에 있다)-->
        <a class="material-icons" style="box-shadow:0 0 4px #ccc; border-radius:10rem; padding: .4rem;" href="{% url 'accountapp:update' pk=user.pk %}">
                settings <!-- 모두 소문자이다 -->
        </a>
        <a class="material-icons" style="box-shadow:0 0 4px #fcc; border-radius:10rem; padding: .4rem;" href="{% url 'accountapp:delete' pk=user.pk %}">
                delete_forever
        </a>
        {% endif %}
    </div>
</div>


    
     <!-- 해당 계정의 글 목록을 보여주기-->
<div>
    {% include 'list.html' with article_list=object_list %}
</div>







{% endblock %}

blog/accountapp/templates/accountapp/hello_world.html
{% extends 'base.html' %}
 
<!-- 어떻게 base.html만으로 경로를 아냐? 왜냐하면 setting.py에서 TEMPLATE = ['DIRS': [os.path.join(BASE_DIR, 'templates')]]로 경로를 blog/blog/templates로 지정했기 때문에.-->

{% block content %}
<!-- 여기서 바꾼 내용이 base.html 안의 content 블럭으로 들어간다 -->
<div style="border-radius:1rem; margin:2rem; text-align:center;">
    
<h1 style="font-family: 'Lobster', cursive;">
    DB List
    </h1>
    
    
    <form action="/account/hello_world/" method="post">
        <!-- post 쓸 때는 꼭 아래의 csrf token 써야 오류가 안 난다-->
        {% csrf_token %}
        <div>
            <input type="text" name="hello_world_input">
        </div>
        
        <div>
            <input type="submit" class="btn btn-primary" value="POST">
        </div>
        
        
    </form>
    
    
    {% if hello_world_list %} <!-- hello_world_output 객체가 존재하는지 확인-->
    
    	{% for i in hello_world_list %}
    
    	<h4>
        {{ i.text }} <!-- view에서 return한 데이터 등에서 text라는 이름을 가진 객체의 값을 가져온다-->
    	</h4>
    	{% endfor %}
    {% endif %}
    
    
    
</div>



{% endblock %}

blog/accountapp/templates/accountapp/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
<div class="dove_500px_div">
    <div>
        <h4>Login</h4>    
    </div>
    <div>
        <form action="{% url 'accountapp:login' %}" method="post">
            {% csrf_token %}
            <!--{{form}}-->
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3" value="로그인"> <!-- btn (버튼 색) (모양) (열 너비(12가 100%)) (margin-top (기존 마진의 3배))-->
        </form>
        <div style="margin-top:1rem;">
            <h7>
                또는 소셜 계정으로 로그인
            </h7>            
        </div>

        {% include 'socialauth/login.html' %} <!-- include 구문은 자동으로 templates 폴더를 탐색하기 때문에 "include 앱 이릅/템플릿명"으로만 해도 작동한다.-->
    </div>
</div>

{% endblock %}

blog/accountapp/templates/accountapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
	<div style="text-align:center; max-width:500px; margin:4rem auto;">
        <div class="mb-4">
            <h4>Change Info</h4>
        </div>
        <form action="{% url 'accountapp:update' pk=target_user.pk %}" method="post">
            {% csrf_token %}
            <!--{{ form }}--> <!--views.py의 AccountCreateview 클래스의 UserCreationForm을 그대로 불러온다.-->
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3" value="변경하기">
        </form>
    </div>
{% endblock %}